import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google';
import Header from "./components/Header";
import Footer from "./components/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable:"--font-montserrat",
  fallback: ['Arial', 'sans-serif'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      >
         <Header/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
