// fake-posts.ts
import { Posts } from "./column";

export const fakePosts: Posts[] = [
  {
    _id: "1",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-01-05"),
    trending: true,
    brief: "Basics of price action trading.",
    content: "Price action focuses on raw market movement...",
    img: "https://picsum.photos/400/250?1",
  },
  {
    _id: "2",
    category: "SMC coádoasodoasdash",
    author: "Anh",
    date: new Date("2024-01-07"),
    trending: false,
    brief: "Understanding liquidity in SMC.",
    content: "Liquidity is where smart money targets...",
    img: "https://picsum.photos/400/250?2",
  },
  {
    _id: "3",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-01-10"),
    trending: false,
    brief: "Next.js app router overview.",
    content: "App Router introduces layout-based routing...",
    img: "https://picsum.photos/400/250?3",
  },
  {
    _id: "4",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-01-12"),
    trending: true,
    brief: "Risk management fundamentals.",
    content: "Without risk management traders fail...",
    img: "https://picsum.photos/400/250?4",
  },
  {
    _id: "5",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-01-15"),
    trending: true,
    brief: "What is Fair Value Gap?",
    content: "FVG occurs when price moves impulsively...",
    img: "https://picsum.photos/400/250?5",
  },
  {
    _id: "6",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-01-18"),
    trending: false,
    brief: "Tailwind layout tips.",
    content: "Flex and Grid are core layout systems...",
    img: "https://picsum.photos/400/250?6",
  },
  {
    _id: "7",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-01-20"),
    trending: false,
    brief: "Support & resistance zones.",
    content: "Key levels control price reaction...",
    img: "https://picsum.photos/400/250?7",
  },
  {
    _id: "8",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-01-22"),
    trending: true,
    brief: "Liquidity sweep explained.",
    content: "Liquidity sweep happens before reversal...",
    img: "https://picsum.photos/400/250?8",
  },
  {
    _id: "9",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-01-25"),
    trending: false,
    brief: "React useEffect deep dive.",
    content: "useEffect handles side effects...",
    img: "https://picsum.photos/400/250?9",
  },
  {
    _id: "10",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-01-27"),
    trending: true,
    brief: "Trading psychology.",
    content: "Mindset determines long-term success...",
    img: "https://picsum.photos/400/250?10",
  },

  // ---------- thêm 10 cái nữa ----------
  {
    _id: "11",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-02-01"),
    trending: false,
    brief: "Break of Structure.",
    content: "BOS confirms market direction...",
    img: "https://picsum.photos/400/250?11",
  },
  {
    _id: "12",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-02-03"),
    trending: false,
    brief: "Reusable components.",
    content: "Component reusability reduces bugs...",
    img: "https://picsum.photos/400/250?12",
  },
  {
    _id: "13",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-02-05"),
    trending: true,
    brief: "Position sizing.",
    content: "Position sizing protects capital...",
    img: "https://picsum.photos/400/250?13",
  },
  {
    _id: "14",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-02-07"),
    trending: false,
    brief: "Premium & Discount zones.",
    content: "Trade from premium or discount...",
    img: "https://picsum.photos/400/250?14",
  },
  {
    _id: "15",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-02-10"),
    trending: false,
    brief: "TanStack Table setup.",
    content: "TanStack Table is headless...",
    img: "https://picsum.photos/400/250?15",
  },
  {
    _id: "16",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-02-12"),
    trending: true,
    brief: "Trend continuation strategies.",
    content: "Trade with trend for higher probability...",
    img: "https://picsum.photos/400/250?16",
  },
  {
    _id: "17",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-02-14"),
    trending: false,
    brief: "Internal vs external liquidity.",
    content: "Liquidity exists at multiple levels...",
    img: "https://picsum.photos/400/250?17",
  },
  {
    _id: "18",
    category: "Frontend",
    author: "Anh",
    date: new Date("2024-02-16"),
    trending: false,
    brief: "Client vs Server Components.",
    content: "Server Components reduce JS bundle...",
    img: "https://picsum.photos/400/250?18",
  },
  {
    _id: "19",
    category: "Trading",
    author: "Anh",
    date: new Date("2024-02-18"),
    trending: true,
    brief: "High-probability setups.",
    content: "Patience leads to better setups...",
    img: "https://picsum.photos/400/250?19",
  },
  {
    _id: "20",
    category: "SMC",
    author: "Anh",
    date: new Date("2024-02-20"),
    trending: false,
    brief: "Daily bias with ICT.",
    content: "Bias helps align with smart money...",
    img: "https://picsum.photos/400/250?20",
  },
];
